#!usr/bin/perl
## Copyright (C) 2017 by Wanghao Truly
use 5.010;

$randint=int(1+rand(100));
my $Debug = $ENV{DEBUG} //1;
print "the answer is $randint\n" if $Debug;
while(1){
  print "input a guess  number:";
  chomp(my $guess = <STDIN>);
  print "\n";
  last if $guess=~ /quit|exit|\A\s*\z/i;
  if($guess==$randint){
     print "the guess number  $guess is right \n";
     last;
  }elsif($guess > $randint){
     print "Too hight\n";
  }else{
     print "Too low\n";
  }
}
