#!usr/bin/perl
use 5.010;
use File::Basename;
use File::Spec;


my $symlink = $ARGV[0] eq '-s';
shift @ARGV if $symlink;

my($source,$dest)=@ARGV;

if(-d $dest){
    my $basename=basename $source;
    $dest = File::Spec->catfile($dest,$basename);
}

if($symlink){
    symlink $source, $dest  or die "Can't soft link '$source' to '$dest': $!\n";
}else{
    link $source, $dest  or die "Can't link '$source' to '$dest': $!\n";
}
