#!usr/bin/perl
## Copyright (C) 2017 by Wanghao Truly
use 5.010;

say "Checking the number <$ARGV[0]>";

sub divisors{
   my $number = shift;
   my @divisors=();
   foreach my $divisor (2..($number/2)){
      push @divisors,$divisor unless $number % $divisor;
   }
   return @divisors;
}

  
given($ARGV[0]){
   when(!/\A\d+\Z/){ say "not a number"}

   my @divisors= divisors($_);
  
   my @empty;
   when(@divisors ~~ @empty){ say "Number is prime!"}
   default {say "$_ is divisible by @divisors";}
}
