#!usr/bin/perl
## Copyright (C) 2017 by Wanghao Truly
use 5.010;

  
for(@ARGV){
   say "Processing $_";
 
   when(! -e){ say "\t File does not exist";continue}
   when(-r _){ say "\t Readable!";continue}
   when(-w _){ say "\t Writeable";continue}
   when(-x _){ say "\t Executable!";continue}
}
