#!usr/bin/perl
## Copyright (C) 2017 by Wanghao Truly
use 5.010;

$randint=int(1+rand(100));
print "the answer is $randint\n";
while(1){
  print "input a guess  number:";
  chomp(my $guess = <STDIN>);
  print "\n";
  last if $guess=~ /quit|exit|\A\s*\z/i;
  
  given($guess){
     when($guess == $randint){
        print "the guess number  $guess is right \n";
        last;
     }
     when($guess > $randint){
        print "Too hight\n";
     }
     default{
        print "Too low\n";
     }

  }
}
