#!usr/bin/perl
## Copyright (C) 2017 by Wanghao Truly
use 5.010001;

my $filename= '';
open my $fh,'<',$filename or die "Can't open '$filename': $!";

chomp(my )


chdir '/' or die "Can't chdir to root directory:$!";

exec 'ls','-l' or die "Can't exec ls: $!";
