#!usr/bin/perl

@names=qw/ fred betty barney dino wilma pebbles bamm-bamm/;
print "input some numbers from 1-7, then press Ctro-D:\n";
chomp(@numbers=<STDIN>);
foreach(@numbers){
   print "@names[$_ - 1]\n";
}
