#!usr/bin/perl
use 5.010;

print "What column width would you like?";
chomp($width=<STDIN>);

print "Enter some lines,then press ctrl+D: \n";
chomp(my @lines=<STDIN>);

print "1234567890" x 7,"12345\n";
foreach(@lines){
   printf "%${width}s\n",$_;

}
