#!usr/bin/perl
use 5.010;

my(@words,%count,$word);
chomp(@words= <STDIN>);

foreach $word(@words){
   $count{$word}+=1;
}

foreach $word(keys %count){
   print "$word was seen $count{$word} times.\n";
}
